### ISSUE TITLE
Why is the DPT value of a received telegram always "no_dpt"?

### ISSUE THREAD

**Issue by Bouni** [estbeetoo/node-red-contrib-knx#13]
Why is it that you set the DPT of received telegrams to *no_dpt*?

https://github.com/estbeetoo/node-red-contrib-knx/blob/925a2aa1c1d45e80a4b33d61233635872ae70716/knx.js#L300

**Comment by aborovsky** [comment]
Hello, Bouni!
As i remeber, that's because underlying knx.js driver is pretty simple and didn't parsing incoming data.
It didn't try to determine DPT type on the basis of data shape, too.

Please, take a look at: https://github.com/estbeetoo/knx.js/blob/873debcfe8e64cac70f957b37ddb2be6912ec759/src/KnxReceiver.js#L8

So, we assume, you know exactly what type of DPT is coming for specified group address.
It's not cool, but it as simple as even may be possible.

Cause you are the owner of ETS project :)

**Comment by Bouni** [comment]
Hi, 

I just took a quick look at how a telegram is actually shaped and as far as I understand, the DPT is not transmitted. 
So you're absolutely right, I have to know what kind of DPT a certain GA is.
