### ISSUE TITLE
Can't send DPT9 float value

### ISSUE THREAD

**Issue by niko2206** [estbeetoo/node-red-contrib-knx#2]
Hello! I get an error when I try to send a DPT9 float value, DPT1 and 5 work!

Thank you for your work, this is exactly what I needed for my home automation!

> 12 Sep 15:56:19 - [info] [knx-out:ee54a9f7.d0b0e8] knxout.onInput, msg[{ topic: '',
>   payload: { dstgad: '2/2/3', value: '23.1', dpt: '9' },
>   _msgid: 'b1f39066.4e0c7' }]
> 12 Sep 15:56:19 - [info] [knx-out:ee54a9f7.d0b0e8] groupAddrSend action[write] dstgad:2/2/3, value:23.1, dpt:9
> 12 Sep 15:56:19 - [info] [knx-controller:3d6dbfcc.b2ac48] connecting to knxjs server at 192.168.0.11:3671 in mode[tunnel/unicast]
> 12 Sep 15:56:19 - [info] [knx-out:ee54a9f7.d0b0e8] sendAPDU: 23.1
> 12 Sep 15:56:19 - [error] [knx-out:ee54a9f7.d0b0e8] error calling groupAddrSend: TypeError: Cannot read property 'writeFloatLE' of null
> 12 Sep 15:56:19 - [error] [knx-out:ee54a9f7.d0b0e8] groupAddrSend error: [TypeError: Cannot read property 'writeFloatLE' of null]
> 12 Sep 15:56:19 - [info] [knx-controller:3d6dbfcc.b2ac48] Knx: successfully connected to 192.168.0.11:3671 in mode[tunnel/unicast]

**Comment by aborovsky** [comment]
Thank you for reply!
I'll try to reproduce your issue on Monday.

May I ask you about your home project? :)

It's quite unusual: somebody who able to do DIY projects and integration,
owns KNX-based (not cheap, for sure) devices at home. What is your story? :)

Сб, 12 сент. 2015 г. в 17:13, niko2206 notifications@github.com:

**Comment by niko2206** [comment]
I completely renovated my house after I bought it. So I had to do all the electric new. I didn't want to do it the conventional way but have some sort of automation. KNX was the best wired solution for my needs and I liked the Gira Homeserver a lot. At the time I had the opportunity to buy lots of the parts for a very low price...;)
NowI want to integrate other things like Homematic wireless products.
I your project not a private one but business?

**Comment by aborovsky** [comment]
My project is both private and business.
What I mean: we are successfully implementing project based on different appropriate software+hardware technologies from automation market (crestron,amx,wago,gira[homeserver too],abb,evika,iridium, etc.).

And always was a dream - install our own solutions at home.
But it's requiring to install expensive hardware - this is a stopper.

That's why we are trying to research an ability: replace proprietary login controllers with opensource-based software controller, like a Node-RED.

For example, we believe: you able to throw away gira homeserver [sorry for that :) ] and replace it with intel nuc (or zotac zbox) with Node-RED installed. It will be the core of unsptoppable integration of different systems and services.

So, you shrinked you expenses. And it much better to spend money on additional iPads installed in iPort Launchport. Controlling interface may be implemented as native app or iRidiumMobile solution.

What do you think? Sounds like a charm, doesn't it? =)

**Comment by niko2206** [comment]
Yes it does!

Today I am much more in opensource and free Software. I will take the best parts of everything...;)

Were you able to reproduce the error?

**Comment by aborovsky** [comment]
Yes, we are right now working with problem.
Soon, there will be a result.

пн, 14 сент. 2015 г. в 14:57, niko2206 notifications@github.com:

**Comment by niko2206** [comment]
Hello!

Did you make any progress?

**Comment by aborovsky** [comment]
Hi!

Sorry, but no.
We figure out, that there is a need to implement in JavaScript specfic DPT
(datapoints) to byte array (JS's buffer) translators.
For example, for 2-byte float, this one:
https://github.com/lifeemotions/knx.net/blob/master/src/KNXLib/DPT/DataPoint2ByteFloatTemperature.cs

I've started it. But it will be finished on next week with luck.

Do you have a JavaScript programming skills? May be you able to help us to
develop some functions and contribute to the project? :)

ср, 16 сент. 2015 г. в 13:01, niko2206 notifications@github.com:
