### ISSUE TITLE
error calling groupAddrSend: TypeError: Object has no method 'writeIntLE'

### ISSUE THREAD

**Issue by gjniewenhuijse** [estbeetoo/node-red-contrib-knx#8]
I like to write a knx address to the bus so i add a injector with the following json payload:
{"dstgad":"2/1/19", "value":"0", "dpt":"1"}

But then i receive an error, see atteched screenshot.
![naamloos](https://cloud.githubusercontent.com/assets/1484623/16074907/f259b9a2-32ec-11e6-928f-21aaa1bbc08c.png)

How to solve this?

**Comment by aborovsky** [comment]
Thanks for bug report! Will check it in few days.
Ср, 15 июня 2016 г. в 12:33, Gert-Jan Niewenhuijse <notifications@github.com

**Comment by ykornilov** [comment]
We have tried the same flow and it works

Try to update node-red-contrib-knx:
npm install -g node-red-contrib-knx

Which version Node-red are you using?

**Comment by ykornilov** [comment]
We have tried the same flow and it works

Try to update node-red-contrib-knx:
npm install -g node-red-contrib-knx

Which version Node-red are you using? 
@gjniewenhuijse

**Comment by gjniewenhuijse** [comment]
Hello, i used v0.13.4

Started Node-RED graphical event wiring tool..

# Welcome to Node-RED

17 Jun 06:01:20 - [info] Node-RED version: v0.13.4
17 Jun 06:01:20 - [info] Node.js  version: v0.10.29
17 Jun 06:01:20 - [info] Linux 4.4.11+ arm LE

**Comment by ykornilov** [comment]
Hello!
Object Buffer in Node.js version v0.10.x has no method writeIntLE.
Update Node.js to version v0.12.x
We used version v0.12.7

**Comment by gjniewenhuijse** [comment]
thanks, i give it a try...

**Comment by polarathene** [comment]
@aborovsky I just ran into similar problem myself. I am new to `node-red`. I was able to send message and trigger switch(light on/off) but each time it crash.

It is because of [this line](https://github.com/estbeetoo/node-red-contrib-knx/blob/master/knx.js#L217) I think.

```
[info] [knx-out:TestNodeKNXOutput] sendAPDU: true
20 Jun 07:28:42 - [red] Uncaught Exception:
20 Jun 07:28:42 - TypeError: callback is not a function
    at SendWrap.cb [as callback] (/usr/local/lib/node_modules/node-red-contrib-knx/node_modules/knx.js/src/KnxSenderTunneling.js:40:21)
    at SendWrap.afterSend [as oncomplete] (dgram.js:407:8)
```

Either that or the previous call to Action: `connection.Action(dstgad.toString(), value, null);`, I'm not familiar with node-red, but if null is meant to be a function, that could also be reason it break.

Also on [docs](https://github.com/estbeetoo/node-red-contrib-knx/blob/master/README.md):
`--- dpt: datapoint type (1 for booleans, 5 for 4-bit dimming setpoints etc) - defaults to 1 for boolean on/off GA's`
This does not say it is required. But you can see value is assigned [here](https://github.com/estbeetoo/node-red-contrib-knx/blob/master/knx.js#L169), it is using `.toString()`, this throws error if you do not provide a value, see [here for more info why](http://stackoverflow.com/a/11083415). Use `String(dpt) || '1'` instead if you want to avoid error and also provide default. Your default case for switch statement throws an error as well, perhaps you should add `REQUIRED` to docs?

**Comment by aborovsky** [comment]
@polarathene, first problem 'TypeError: callback is not a function' is fixed. Try to update library to version 0.7.1:
`$ npm install node-red-contrib-knx@0.7.1`

**Comment by gjniewenhuijse** [comment]
problem solved when i update node js.

**Comment by polarathene** [comment]
@aborovsky Works great thanks :)
